export const personalInfo = {
  name: "Gabriel López",
  location: "Santiago, Chile",
  github: "https://github.com/gabo71096",
  linkedin: "https://www.linkedin.com/in/gabo-71096/",
};

export const workExperience = [
  {
    company: "Grupo Amoble",
    location: "Santiago, Chile",
    position: "Full Stack Developer and IT Support",
    period: "July 2024 - Present",
    achievements: [
      "Give support to users about our platforms (POS and PIM) and third party software such as SAP Business One and WMS.",
      "Develop solutions, fix bugs and implement new features as required by the company and its users, using Ruby on Rails.",
      "Deploy changes to production using Git Hooks.",
      "Integrate our platforms with third party software using REST APIs and WebHooks.",
      "Create background tasks for high demanding processes (DelayedJob / GoodJob), and schedule them using cron.",
      "Take full advantage of AI to write code more efficiently, ask relevant questions and boost productivity.",
      "Analyse database performance, create backups and improve slow queries on both MySQL and PostgreSQL engines.",
      "Refactor code to improve legibility and keep codebase DRY.",
      "Participate in code reviews, give/receive feedback in order to continue learning and growing both professionally and personally.",
      "Integrate our applications with AI to automate manual processes and improve the experience of our users.",
    ],
  },
  {
    company: "OA Systems",
    location: "Auckland, New Zealand",
    position: "Dynamics 365 Developer",
    period: "September 2023 - March 2024",
    achievements: [
      "Design and implementation of custom PCF controls using React.",
      "Creation of complex multi-step forms for KiwiRail using Kendo React.",
      "Creation of new API endpoints written on .NET.",
      "Azure Functions development and deployment.",
      "Entity modification on Dataverse.",
      "Migrate from jQuery to React.",
    ],
  },
  {
    company: "Laboratorio GenoSUR",
    location: "Santiago, Chile",
    position: "Full Stack Developer",
    period: "January 2022 - June 2023",
    achievements: [
      "Creation of LIMS software from the ground up using Ruby on Rails, Node.js (Express), jQuery, React, Bootstrap, MySQL, deployed to Google Cloud Platform.",
      "Implementation of API client for Ministry of Health of Chile's COVID reporting using Ruby on Rails.",
      "Creation of reusable UI components with jQuery and React.",
      "Implementation of method for PDF generation with sample results.",
      "Supporting new colleagues, helping them set up their work environments and guiding them through the application and framework.",
    ],
  },
  {
    company: "B2B Tech SPA (Europ Assistance)",
    location: "Santiago, Chile",
    position: "Full Stack Developer",
    period: "April 2021 - January 2022",
    achievements: [
      "UX/UI design on Figma.",
      "Database schema design and optimization on PostgreSQL.",
      "Implementation of inventory report download to Excel spreadsheet using Ruby on Rails.",
      "Administrative platform design for product and user modification using Active Admin (Ruby on Rails).",
      "Setup AWS ECS and PostgreSQL RDS instance for deployment.",
    ],
  },
  {
    company: "Mamá, Te Entiendo",
    location: "Santiago, Chile",
    position: "Full Stack Developer",
    period: "June 2020 - March 2021",
    achievements: [
      "Database schema design and optimization on PostgreSQL.",
      "Implemented responsive UI design using Bootstrap.",
      "Fixed bugs specific to Apple devices.",
      "Implemented mailer service using Action Mailer (Ruby on Rails).",
      "Setup remote Ubuntu server on DigitalOcean and deployment.",
      "Containerize application using Docker and orchestrate it with Docker Compose/Swarm.",
    ],
  },
];

export const education = [
  {
    institution: "Instituto Profesional Providencia",
    location: "Santiago, Chile",
    degree: "Associate Degree in Information Technology",
    period: "2018 - 2022",
  },
];
export const skills = {
  programmingLanguages: [
    "Ruby",
    "Python",
    "TypeScript",
    "C#",
    "HTML",
    "CSS",
    "SQL",
  ],
  frontendDevelopment: [
    "React",
    "jQuery",
    "Bootstrap",
    "Material UI",
    "ChakraUI",
    "ShadCN",
    "TailwindCSS",
  ],
  backendDevelopment: ["Fastify", "Express", ".NET", "FastAPI", "ElysiaJS"],
  fullStackDevelopment: ["Ruby on Rails", "Next.js"],
  databaseAndStorage: [
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Prisma",
    "ActiveRecord",
    "Drizzle",
    "SQLAlchemy",
  ],
  cloudAndDevOps: [
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Digital Ocean",
    "Docker",
    "Swarm",
    "Github Actions",
  ],
};

export const awards = [
  {
    name: "IEEE YESIST12 Hackathon",
    issuer: "IEEE",
    date: "Sep 2022",
    type: "International",
    position: "Second Place",
  },
  {
    name: "Prodigi Cognizant Hackathon",
    issuer: "Cognizant",
    date: "Feb 2023",
    type: "National",
    position: "Second Runner-up",
  },
  {
    name: "Cisco Thingqbator Hackathon",
    issuer: "Cisco",
    date: "Jan 2023",
    type: "National",
    position: "First Runner-up",
  },
  {
    name: "Innovators Day",
    issuer: "Sri Manakula Vinayagar Engineering College, Pondicherry",
    date: "Sep 2022",
    type: "National",
    position: "First Prize",
  },
  {
    name: "KG Hackfest'22",
    issuer: "KGiSL Institute of Technology, Coimbatore",
    date: "Sep 2022",
    type: "National",
    position: "Second Prize",
  },
  {
    name: "Innohacks'22",
    issuer: "Innogeeks, KIET Group of Institutions, New Delhi",
    date: "May 2022",
    type: "National",
    position: "Second Runner-up",
  },
  {
    name: "Hack @ SKCET",
    issuer: "Hackclub SKCET, SKCET, Coimbatore",
    date: "Feb 2022",
    type: "National",
    position: "Most Impactful Hack",
  },
];
